languageCode: vi-vn
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
title: Tuệ An
description: write and share to learn
baseURL: https://tuean.netlify.com/
theme: til
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: UA-131517577-1
paginate: 40
social:
  facebook: 12bit.vn
author:
  email: contact@12bit.vn
  name: 12bit.vn
outputs:
  home:
    - HTML
    - RSS
params:
  description: write and share to learn
  favicon: img/icon/favicon.png
  images:
    - img/index.png
  facebookAppId: 363747664413304

blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true
